# -*- coding: utf-8 -*-
"""data_loader.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-3ikgqV9FwPfSvHJ-CJYtp_To0eRY47-
"""

import requests

API_URL = "https://november7-730026606190.europe-west1.run.app/messages"

def fetch_messages():
    response = requests.get(API_URL)
    response.raise_for_status()
    return response.json()

|