# -*- coding: utf-8 -*-
"""openai_client.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-3ikgqV9FwPfSvHJ-CJYtp_To0eRY47-
"""

import os
from openai import OpenAI

def ask_llm(prompt: str) -> str:
    api_key = os.getenv("OPENAI_API_KEY")

    if not api_key:
        raise ValueError("OPENAI_API_KEY not set. Add it in HuggingFace Secrets.")

    client = OpenAI(api_key=api_key)

    response = client.chat.completions.create(
        model="gpt-4.1",
        messages=[
            {"role": "system", "content": "You answer questions ONLY using the provided member messages."},
            {"role": "user", "content": prompt}
        ],
        temperature=0
    )

    return response.choices[0].message["content"]

|