# -*- coding: utf-8 -*-
"""prompt_builder.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-3ikgqV9FwPfSvHJ-CJYtp_To0eRY47-
"""

import json

def build_prompt(question: str, messages: dict) -> str:
    context = json.dumps(messages, indent=2)

    prompt = f"""
You are a question-answering assistant.

Below is the dataset of member messages (JSON):
------------------------------------------------
{context}
------------------------------------------------

Answer the user's question ONLY using the information above.
If the answer is missing, say: "Information not available."

User question: "{question}"
    """

    return prompt

|